server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
spring:
  # 数据源配置
  datasource:
    name: test
    url: jdbc:mysql://192.168.0.5:3306/manage
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    max-active: 20
    initial-size: 1
    max-wait: 60000
    min-idle: 1
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: select 'x'
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    pool-prepared-statements: true
    max-open-prepared-statements: 20


logging:
  file: biggirlo
  level:
    ROOT: warn
    org.springframework: info
    org.springframework.web.servlet.view: info
    org.springframework.web.servlet.mvc: info
    io.undertow.request: info
    com.biggirlo: debug
    com.einwin.framework.mybatis: debug
    com.github.pagehelper: TRACE
    com.zaxxer.hikari: TRACE