spring:
  # 数据源配置
  datasource:
    name: test
    url: jdbc:mysql://192.168.0.5:3306/manage
    username: root
    password: abc123
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat, wall
    max-active: 20
    initial-size: 1
    max-wait: 60000
    min-idle: 1
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: select 'x'
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    pool-prepared-statements: true
    max-open-prepared-statements: 20

server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

shiro:
  tokenHeaderName: Authorization
  accessControlAllowMethods: POST, GET, PUT, DELETE,OPTIONS
  accessControlAllowHeaders: Authentication,Origin, X-Requested-With, Content-Type,token,Accept,Authorization
  accessControlMaxAge: 3600
  accessControlAllowOrigin: http://localhost:8082

mybatis:
  config:
    # Mybatis model 路径
    typeAliasesPackage: tk.mapper.model,com.tokid.model
    reasonable: true
    supportMethodsArguments: true
    returnPageInfo: check
    params: count=countSql
    # Mybatis mapper xml 路径
    mapperLocations: classpath:mapper/*.xml
    # Mybatis mapper interface 路径
    basePackage: com.tokid.mapper
    # 通用 mapper 接口
    mappers: tk.mybatis.mapper.common.Mapper
    # 主键自增全局配置
    identity: MYSQL
    logImpl: STDOUT_LOGGING

logging:
  file: logs/tokid.log